import * as cdk from "aws-cdk-lib"
import * as dynamodb from "aws-cdk-lib/aws-dynamodb"
import * as ssm from "aws-cdk-lib/aws-ssm"
import { Construct } from "constructs"

/**
 * Properties for the SeverityExamplesStack.
 *
 * @property prefix - Resource name prefix (e.g. "team5"). Used to namespace
 *   the DynamoDB table name and SSM parameter path. There is no default —
 *   callers must supply a value explicitly.
 */
export interface SeverityExamplesStackProps extends cdk.NestedStackProps {
  /** Resource name prefix — must be provided by the caller. */
  readonly prefix: string
}

/**
 * CDK nested stack that provisions the Severity_Examples_Store DynamoDB table
 * and publishes its table name to SSM Parameter Store.
 *
 * Resources created:
 *   - DynamoDB table  `{prefix}-severity-examples`
 *       Partition key : `exampleId` (String)
 *       GSI           : `severity-createdAt-index`
 *                        Partition key `severity` (String), Sort key `createdAt` (Number)
 *   - SSM parameter   `/{prefix}/severity-examples-table-name`
 *       Stores the physical DynamoDB table name so other stacks / Lambdas can
 *       discover it at deploy-time or runtime.
 *
 * Follows the FAST template patterns:
 *   - Nested stack (same as BackendStack, CognitoStack, AmplifyHostingStack)
 *   - PAY_PER_REQUEST billing for zero-cost at rest
 *   - Point-in-time recovery enabled
 *   - AWS-managed encryption
 *   - DESTROY removal policy (safe for dev / hackathon stacks)
 *
 * Requirements satisfied: 7.1, 7.2, 7.3
 */
export class SeverityExamplesStack extends cdk.NestedStack {
  /** The DynamoDB Table construct — exposed so other stacks can grant permissions. */
  public readonly table: dynamodb.Table

  /** The physical DynamoDB table name (convenience accessor). */
  public readonly tableName: string

  constructor(scope: Construct, id: string, props: SeverityExamplesStackProps) {
    super(scope, id, props)

    const { prefix } = props

    // ── DynamoDB table ──────────────────────────────────────────────────
    this.table = this.createSeverityExamplesTable(prefix)
    this.tableName = this.table.tableName

    // ── SSM parameter ───────────────────────────────────────────────────
    this.storeSsmParameter(prefix)
  }

  /**
   * Creates the Severity_Examples_Store DynamoDB table.
   *
   * Table schema mirrors the data model in the design doc:
   *   - `exampleId`  (String)  — partition key, UUID generated by the Admin API
   *   - `severity`   (String)  — one of low | medium | high | critical
   *   - `createdAt`  (Number)  — epoch milliseconds, used as sort key in the GSI
   *
   * A Global Secondary Index (`severity-createdAt-index`) enables efficient
   * queries filtered by severity level, ordered by creation time.
   *
   * @param prefix - Resource name prefix (e.g. "team5")
   * @returns The DynamoDB Table construct
   */
  private createSeverityExamplesTable(prefix: string): dynamodb.Table {
    const table = new dynamodb.Table(this, "SeverityExamplesTable", {
      tableName: `${prefix}-severity-examples`,
      partitionKey: {
        name: "exampleId",
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true,
      },
      encryption: dynamodb.TableEncryption.AWS_MANAGED,
    })

    // GSI: enables GET /examples?severity=<value> queries ordered by createdAt
    table.addGlobalSecondaryIndex({
      indexName: "severity-createdAt-index",
      partitionKey: {
        name: "severity",
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: "createdAt",
        type: dynamodb.AttributeType.NUMBER,
      },
      projectionType: dynamodb.ProjectionType.ALL,
    })

    return table
  }

  /**
   * Stores the DynamoDB table name in SSM Parameter Store under the
   * `/{prefix}/` namespace so that Lambda functions and agents can
   * discover it at runtime without hard-coding.
   *
   * @param prefix - Resource name prefix (e.g. "team5")
   */
  private storeSsmParameter(prefix: string): void {
    new ssm.StringParameter(this, "SeverityExamplesTableNameParam", {
      parameterName: `/${prefix}/severity-examples-table-name`,
      stringValue: this.table.tableName,
      description:
        "DynamoDB table name for the Severity_Examples_Store used by the Classification_Agent and Admin API",
    })
  }
}
